


0 = ""


929 = "ユイ"
969 = "先輩兵士"
1052 = "男小隊長"
974 = "兵士達"
975 = "兵士Ａ"
931 = "ロボット兵"
924 = "ヤエカ"
1076 = "街頭演説の人"
1065 = "義母"
913 = "アカリ"


1108 = "？？？"
999 = "小隊長"
973 = "兵士"
1077 = "見知らぬ人"






828 = "この世界は、ろくなものじゃない。"




517 = "「……っ」"



1055 = "砲弾が頭上を飛ぶ音と、爆発の衝撃。"



978 = "内臓を震わす重低音に、身体がすくみ上がった。"



755 = "「今のは大丈夫だぞ。味方の砲撃だ」"




539 = "「あ……は、はいっ」"



787 = "「準備は？」"




609 = "「せ、整備終わりました」"



798 = "「見せてみろ」"



1080 = "言われた通りに、組み立て終わった古い小銃を兄貴に渡す。"



525 = "「……よし。持ち場に着くぞ」"




681 = "「はいっ……」"



961 = "僕の小さな手に、ずっしりと重たい鉄製の銃が戻ってくる。"



560 = "「あんまり頭を出すんじゃないぞ。そーっとだ」"




731 = "「わ、わかってます」"



998 = "小銃を抱え、塹壕の壁にある段差へとよじ登る。"



915 = "コーリョクシャが始まったのか、僕達が張り付いている\\n壁の向こう側で、何度も何度も爆発が起きていた。"



805 = "「頼むぜ、全滅しててくれよ……」"



911 = "やがて連続した爆発が収まると、土嚢の溝に銃身を乗せ、\\nそっと頭を出して目をこらす。"



526 = "「……嘘だろ」"




606 = "「す、すごいいっぱいいます……！」"



799 = "「見りゃ分かる。初弾装填！」"




683 = "「はいっ」"



993 = "壊れた仲間を踏み潰して進む、ロボットの大群。"



984 = "原っぱを埋め尽くすような数に、手が震えそうになる。\\n何度も練習していなければ、銃を落としていたかも知れない。"




713 = "「まだだ、まだ撃つなよ……。\\n重機が撃ち始めてから、弾幕を抜けて来た奴を狙うんだ」"



1094 = "隊長さんの指示に頷き、お腹が痛くなってくるのを我慢する。\\n怖くて泣きたかったけれど、それもどうにか我慢した。"




515 = "「……こんな子供まで最前線に立たせなきゃならんとはな」"



958 = "僕のことかな……と思った瞬間。"



1001 = "左右の銃座から、いくつもの機関銃が火を噴いた。"



1088 = "重機関銃のでっかい弾丸に貫かれ、ロボット達に大穴が開く。\\n手足が弾け、ちぎれ飛んでいく。"




780 = "「撃ち方始め！」"



11 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;これが、僕の初陣だった。"



955 = "何も分かってはいなかった。"



872 = "ただ命令されるままに引き金を引くだけで、戦略も、戦術も、\\n戦う理由すら理解していない、ただの子供だった。"



863 = "それどころか、最も身近な問題%p-1;%fＭＳ ゴシック;――%p;%fuser;死の恐怖すら、\\n目の当たりにするまで想像でしかなかったんだ。"




737 = "「ガッ……！？」"



773 = "「小隊長殿！」"




581 = "「えっ、えっ……？」"



959 = "僕のすぐ側で、真っ赤なものが飛び散った。\\nついさっきまで『あそこを狙え』と指示していた隊長さんの、\\n首から上が無くなっていた。"



16 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;混乱している間にも、ロボット達は近づいてくる。"



1085 = "近くの味方は少ないのに、みんなこっちに向かってくる。\\n全部やっつけるのはどう考えても無理だった。"



982 = "十分に近づいたロボット達が、\\nこっちが撃った弾なんて無視して銃口を向けてくる。"



739 = "「バカ、頭下げろ！」"



966 = "兄貴に服を引っ張られ、転げるように塹壕の中に倒れた。"



933 = "一瞬前まで僕がいた辺りを、何発もの銃弾が通り過ぎていく。"



763 = "「危ないところだったぞ、ユイト」"




540 = "「あ……わ……」"



594 = "「これ以上は無理だな……どうせこっちは前哨だ、下がろう」"




562 = "「い、いいんですか？」"



758 = "「俺達はそういう役割だよ。\\n小隊長殿戦死！　指揮を引き継ぐ！　後退用意！」"



875 = "だけど、その命令はたぶん、ほんの少しだけ遅すぎて。"



590 = "「ぐあっ！？」\\n「あっ……！」\\n「ぎゃあっ！？」"



904 = "まだ壁に張り付いて銃を撃っていた大人達が、\\n次々と血しぶきをまき散らして落ちてくる。"




738 = "「ダメだ！　突破される……！」"



952 = "何か、重たいものが落ちるような音がした。\\n鉄の塊みたいな、そしてバネが軋むような音が。"



1030 = "振り向くと、そこに、いた。"



1018 = "感情のこもらない赤い目が、じっと僕を見つめている。\\n銃口が真っ直ぐに、僕の額を狙っている。"



507 = "「…………」"



1087 = "逃げられない距離。股間が生温かくなるのを感じた。"




537 = "「あ……あ……」"



816 = "おしっこを漏らしながら死ぬなんて、かっこ悪い。\\nそう思いながら、僕は%p-1;%fＭＳ ゴシック;――"



994 = "大きく身体が傾くのを感じて、ハッとする。"



511 = "「……おーい、ユイちゃん？」"



691 = "「ふぁ……、えっ……あ……」"



808 = "ああ、今のは夢か%p-1;%fＭＳ ゴシック;――%p;%fuser;と理解した。"



644 = "「だいじょぶ？　なんか、うなされてたけど」"



569 = "「う、うん……ごめん」"



1007 = "心配そうな顔つきで、ヤエカが僕の顔を覗き込んでくる。\\n生意気な義妹がこんな顔をするなんて、よっぽどだったの\\nだろう。"



712 = "「また、怖い夢でも見ちゃった？」"



522 = "「……まあ、そんなとこ。昔のこと、思い出しちゃって」"



630 = "「そっか」"



1040 = "死にかけた経験には事欠かないものだから、\\n悪夢にうなされて目を覚ますことは珍しくもない。"



868 = "そんな僕をずっと近くで見てきたからか、\\nヤエカはそれ以上深く問いただしてはこなかった。"



870 = "ただ、確かめるように視線を僕の顔から下半身へと\\nずらしていって%p-1;%fＭＳ ゴシック;――"



659 = "「とりあえず、大惨事にはなってない……よね？」"



531 = "「……！！？」"



1021 = "慌てて股間を押さえ、下着の中の感触を確かめる。"



503 = "……幸いにも、湿った感触はしなかった。夢の内容が盛大に\\n漏らした時のものだったから、割と真面目に安堵した。"



564 = "「いやー、ちょっと前までうなされてる時はちょくちょく\\nおねしょしてたし？　お兄ちゃんも成長したねぇ～」"



723 = "「もう、バカにして……！　最後にやったのは何年も前だよ！」"



626 = "「そだっけ？　ヤエカ～どうしよぉ～って、べそかいてたの、\\n昨日のことみたいに思い出せちゃう」"



589 = "「お願いだから忘れてよぉ……」"



696 = "「ふっふっふ、お母さんにバレないように乾かすの、\\n手伝ってあげたよね～？　あの時の借りを返したら\\n考えてあげよう」"



779 = "「手伝ってはくれたけど結局バレたじゃん！」"



740 = "「バレたけど、貸しは貸し。きっちり返してもらうから」"



672 = "「なんてがめつい義妹……」"



874 = "ため息を吐いてみせるけど、内心分かってはいるつもり。"



825 = "こうやってからかうことで、１秒でも早く悪夢の記憶から\\n気を逸らそうとしてくれているのだろう。"



803 = "「都会なら、甘ーいお菓子とかきっと沢山あるよね？\\n何奢ってもらおうかな～」"



498 = "……これでも慰めてくれているのだ、たぶん。きっと。"



658 = "「ところで、この電車止まっちゃってる？」"



575 = "「うん、安全確認だって。今度は信号機が壊れちゃったみたい」"



597 = "「さっきはポイント故障で止まってたよね……\\n今日中に着くかな？」"



558 = "「あとちょっとだし大丈夫だよ。\\n歩くよりは速いし楽ちんだし、しょーがないって」"



711 = "「まあね……でも、早めに出てきてよかったかも」"



1070 = "肩をすくめて、朝からずっと乗っている電車の中を見渡す。\\n少なくともこの車両には、僕達２人だけだった。"



584 = "「お、動き出した。直ったかな？」"



519 = "「……でも、おっそ」"



980 = "動き出したはいいものの、徐行だった。\\n歩くよりは速いけど、走ったら追いつけそうな速度だ。"



791 = "「直らなかったから、ゆっくり行くことになったかー」"



623 = "「そしてこんなスピードでも結構揺れる……」"



806 = "「１００年以上前の電車でしょ？\\n動いてるだけでも奇跡みたいなもんじゃない？」"



706 = "「まあ……ね。世も末だなぁ」"



757 = "「何を今さら」"



850 = "そう言ってヤエカは笑った。\\nこの前向きな性格は、正直ちょっと羨ましいと思う。"



521 = "「……ねえ、ヤエカ。本当に一緒に来るつもりなの？」"



634 = "「それこそ今さらじゃん。もう入学手続きしちゃったし」"



716 = "「まだ間に合うって。僕の方は召集だから仕方ないけど、\\nヤエカは違うんだし……何も志願なんてしなくても」"



536 = "「『僕』は禁止。何回も練習したでしょ？」"



568 = "「う、うん……。えっと、私は……選択の余地ないけど」"



641 = "「そーゆーとこ。ユイちゃん一人で行かせるとか不安すぎる。\\nボクがついてないと、そっこーバレそうじゃん？」"



745 = "「ヤエカは一人称変えないんだ？」"



792 = "「相対的にユイちゃんが女の子っぽく見えるかもだし」"



615 = "「そう、上手くいくかなぁ……」"



936 = "不意に、窓の外が真っ暗になった。トンネルに入ったらしい。"



1058 = "窓に映った自分の姿を、じっと見つめる。"



516 = "「……ちゃんと、女の子らしくなってる？」"



774 = "「少なくとも、ボクより美人のお姉さんにはなってる」"



741 = "「ホントに？」"



782 = "「本当だってば。元々素材はいいんだし、\\nちゃんとメイクして変なことしなければバレないよ」"



764 = "「変なことって？」"



801 = "「足広げて座ったり」"



529 = "「……気を付ける」"



1014 = "意識して、座り姿勢を内股にする。\\n確かに、自分一人きりだと不安かも知れなかった。"



767 = "「大丈夫。ちゃんと見てるし、変だったら言うから」"



508 = "「……ありがと。頼りにしてる」"



917 = "スイーツがあったら高くても奢るくらいは、仕方ないと思った。"



704 = "「ま、別にユイちゃんのためだけってわけでもないし？\\n無事に卒業したら自動的に公務員だし、士官サマにだって\\nなれるんでしょ？　将来安泰じゃん」"



698 = "「ふふ……そうだね」"



1061 = "素直にお礼を言ったら照れたのか、\\nちょっと早口になってそっぽを向くヤエカだった。"



528 = "「……大丈夫。お兄ちゃんのこと、守るから」"



743 = "「ヤエカ。『お兄ちゃん』は%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



761 = "「分かってる。これが最後だから」"



510 = "「……うん」"



964 = "僕達が向かうのは、この国の首都『新東京市』。\\n今の時代に残された、数少ない都市と呼べる街。"



859 = "その街で、僕達は学校に通う。\\nお国からの命令だから、拒否権なんてものはない。"



970 = "入学案内に書かれている校名は、\\n『国家保安隊附属アカシア女子学園』。"



1033 = "未来の武装警察%p-1;%fＭＳ ゴシック;――%p;%fuser;兵士を育てる、女の子だけの学校だった。"



1031 = "故郷を出た今、頼りになるのはヤエカ一人きりだった。"



499 = "……でも、大事な義妹を兵士になんかしたくはなかった。"



928 = "ヤエカは、知らないから志願なんて出来るんだ。"



1024 = "戦うのは怖いし、死ぬのはもっと怖い。\\n直面した経験があるからこそ、誰よりもよく知っている。"



497 = "……あの時は、どうして助かったんだっけ。"



847 = "そうだ、兄貴が……面倒を見てくれていた先輩の兵士が、\\n命がけでロボットに突進して蹴飛ばしてくれたんだ。"



13 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;今はもういない、最初の『家族』だったあの人が。"



890 = "どうして、僕だけが生きているんだろう。"



907 = "みっともなく足掻いて、色んな人に迷惑をかけて、\\n苦しくて、悲しくて、怖くて、きっといつかは失敗して、\\n絶望するに違いなくて……。"



862 = "それでも生き続けるのは、なんのためなんだろう？"



906 = "まるで分からないけど……まだ、諦められない。"



1050 = "生き残ってしまった以上、命がけで助けてもらった以上、\\n粗末に捨て去るわけにはいかなかった。"



950 = "何か、見つけることができるのだろうか？\\n生まれてきた意味……みたいなものを。"



827 = "このろくでもない世界に、そんなものはあるのだろうか？"



502 = "……分からない。何も分からない。"



585 = "「おおー、すごい。おっきい建物がいっぱいだ」"



567 = "「う、うん……。いっぱいだね……」"



655 = "「でもよく見るとボロボロだー」"



661 = "「ど、どれも古い建物だと思うから……」"



752 = "「人はいっぱい歩いてるね。賑やか！」"



614 = "「そう、だね……賑やかで……」"



1099 = "駅の建物を出て、都会の光景にはしゃぐヤエカの後ろで、\\n僕はなるべく目立たないように体を縮こまらせていた。"



748 = "「ユイちゃん、何隠れようとしてんの。流石にウザイ」"



621 = "「そう言われても、人がいっぱいだから……！」"



750 = "「ユイちゃんの方が大っきいんだから、\\nボクの背中にひっついても全然隠れられてないでしょ」"



611 = "「そ、そう……？　そっか……」"



652 = "「ていうか、そんなオドオドしてたら余計に目立つだけ」"



678 = "「はい……ごめんなさい」"



891 = "どうにか勇気を出して背筋を伸ばす。\\nぺっちゃんこの胸が変に見えないか、不安で仕方がない。"



701 = "「ぺちゃぱいはボクも一緒だから心配いらないって」"



989 = "周りと比較して胸を気にしているのに気づいたのか、\\nヤエカが苦笑しながら慰めてくれる。"



572 = "「うん、ありがと……そうだよね」"



665 = "「なにおう！？　誰がぺちゃぱいだ！」"



794 = "「自分で言ったんでしょっ！　ハッ……」"



995 = "大きな声を出してしまい、注目を浴びて再び縮こまる。"



638 = "「そんなに緊張しなくても大丈夫だってば」"



620 = "「そう言われても……」"



876 = "だって、こんなにもたくさんの女の人が行き交っているんだ。"



946 = "今まで住んでいた辺境の村はそもそも人がまばらだったし、\\n数少ない住人も皺だらけのご老人ばかりだったから、まだ\\n大丈夫だった。"



823 = "けれど、こんな大人数の中に身を置いていると、\\n自分の異質さを意識せざるを得ないわけで……。"



595 = "「ご通行中の皆様！　母なるＡＩ民主党、ＡＩ民主党です！\\nお騒がせしておりますが、少しばかり足をお止めになって\\n私共の話をお聞き下さい！」"



882 = "と、マイクとスピーカーを通した大きな声が聞こえてくる。"



586 = "「おおー、街頭演説ってやつ？　初めて見た！」"



802 = "「辺境だと外で喋っても誰もいないからね……」"



789 = "「皆様、今年がどのような年にあたるかをご存知でしょうか？\\nそうです、現代社会の根幹たる『男女隔離法』の制定から\\n今年でちょうど５０年になるのです」"



753 = "「今から５０年前、偉大なるＡＩ『マザー』の提言により\\n『男女隔離法』は成立、いくつかの困難はありましたが\\n厳密に施行されることとなりました」"



636 = "「それまでの歴史において、すべての女性が男性という性別に\\n虐げられ続けてきたことは、皆様もご存知でしょう」"



639 = "「そんな苦難の歴史から我々を解放して下さったのは、\\n女性の女性による、女性の為の楽園を創造して下さったのは、\\nすべて母たるＡＩ『マザー』なのです……！」"



534 = "「『マザー』を称えましょう！　感謝を捧げましょう！\\nそして偉大なるＡＩの意志を、我々は正しく受け止めねば\\nなりません！」"



1035 = "次第に熱を帯びていく演説は、どうやらこの国の\\n社会管理ＡＩ『マザー』を信仰している人達のものらしい。"



948 = "伝統宗教の衰退した現代では、主流の信仰形態だ。\\n……思うところはあるが、信教の自由は当の『マザー』に\\n保証されている。"



532 = "「『マザー』が与えたもうた『男女隔離法』は、果たして\\n何を意味するのでしょうか？　それは、首都を任された\\n我々女性こそが、選ばれた性別であるということです！」"



666 = "「なのに、邪悪な男達は未だにその立場を理解していません。\\n男性区域に近い辺境では、口に出すのもおぞましい事件が、\\n性被害が今日も繰り返されています」"



775 = "「忘れてはいけません、男達はいつ我々女性に\\n牙を向けてくるかわからないのです！」"



771 = "「守らねばなりません！　女性の権利を……！\\nやり遂げましょう、邪悪な男達への鉄槌を！」"



530 = "「……行こう、ヤエカ」"



734 = "「わっ、ちょっとユイちゃん？」"



1044 = "演説から目を背け、ヤエカの手を引いてその場を離れる。"



17 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;足早に歩きながら見渡すと、そこにはたくさんの女の人。"



856 = "その中に男性は一人もいない。\\nだってこの街には、女の人しかいないのだから。"



877 = "つまりは、そんな女性のための巨大な街の中で……\\n僕一人だけが、男だった。"




676 = "「はぁっ……はぁっ……」"



1101 = "鬱蒼と茂る笹やぶをかき分けて、必死に歩き続ける。"



909 = "もう何日山の中を彷徨っているだろう。"



884 = "とうに食料は尽き、かろうじて湧き水で腹を満たしながら、\\nフラフラと目的もなく進み続けている。"



15 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;所属していた部隊は、全滅した。"



967 = "兄貴も僕の目の前で死んだ。\\nおそらくは、生き残っているのは自分だけだ。"



1074 = "行くあてはない。でも立ち止まれば、\\nきっと追いかけてくる連中に殺される。"



500 = "……もしかしたら、その方が楽になれるのかもしれない。"




555 = "「あっ……」"



1004 = "後ろ向きなことを考えた瞬間、木の根っこにつまづいた。\\n受け身も取れずに倒れ込み、身体のあちこちに激痛が走る。"




523 = "「……もう、歩けない」"



1081 = "言葉にした瞬間、それは現実になった。"



1092 = "限界を超えた疲労が一気に襲ってきて、\\n急速に意識が薄れていく。"




505 = "「………………」"




800 = "「誰か……たすけて…………」"



10 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;このまま死ぬのだと、覚悟は決めていた。"



879 = "でも、死ぬのは怖い。死にたくない。"



865 = "そんな、ただ情けないだけの気持ちで呟いた一言を、\\n神様は聞いていてくれたのかもしれない。"




566 = "「ぅ……あ………………」"



1016 = "意識を取り戻した時、瞼を開いて視界に入ったのは、\\n見知らぬ天井だった。"




524 = "「……よかった。目が覚めたのね」"




576 = "「え…………」"



854 = "そして、見慣れない……なんだか不思議な雰囲気の人が、\\n僕の顔を覗き込んできた。"




592 = "「ここ……は……、僕は…………」"




593 = "「ここは私の家。あなたは、山の中で倒れていたのよ」"




610 = "「そ……う……」"




796 = "「衰弱していたし、怪我もたくさんしていて……\\nあのままだと危なかったわ」"



14 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;意識がハッキリしてくると、気がついた。"



1090 = "長い髪、滑らかな肌、小柄で丸みを帯びた体つき。\\n胸の辺りにある、大きな膨らみ。この人は、女だ。"




518 = "「……っ！！！」"




650 = "「ちょっ、ちょっと！　まだ動いちゃダメ！」"



1022 = "慌てて逃げだそうとするけれど、押しとどめられる。\\nビックリするほど全身が痛くて動かなかったから、\\nそっと押されるだけで再びベッドに寝かされてしまった。"




663 = "「な、なんで……女が……」"




618 = "「そう言うあなたは、男の子なのよね……？\\nでも、大丈夫……大丈夫よ。私は敵じゃないわ」"



849 = "そう言って、手を伸ばしてくる。頬に触れてくる。"




735 = "「ん……ぅ…………」"



1082 = "身をすくめて、必死に震えを抑えて、それから目を丸くした。"



901 = "ひんやりして、それでいて柔らかい手の感触が、\\n兄貴達のごつごつしたものとまるで違っていたから。"




765 = "「大丈夫……怖くないから、ね？」"




762 = "「助けて、くれたんですか……？」"




770 = "「子供が山の中で倒れていて、放ってはおけないもの」"




766 = "「大丈夫、私は味方だから……きっと、助けてあげるから」"



12 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;はじめて、女の人と言葉を交わした。"



1042 = "残虐で恐ろしい存在のはずなのに、その人は優しかった。"



1027 = "抱きしめられるともう何もかもが柔らかくて、\\n甘い匂いがして……何故だか泣き出しそうになった。"




541 = "「あ……何か食べられる？　まずは栄養を付けなくちゃ」"




747 = "「ヤエカ～、そんなとこに隠れてないで、手伝って頂戴」"



501 = "……僕は、女の人に助けられ、匿われることになった。"



991 = "命を救ってくれたその人こそが、２番目の『家族』。\\n大好きになったお義母さん%p-1;%fＭＳ ゴシック;――%p;%fuser;ヤエカの母親だった。"



1066 = "義母さんはあの時の言葉の通り、\\n僕の正体を隠して、今日まで育ててくれた。"



831 = "ご近所が記憶力の怪しい老人ばかりの環境だったとはいえ、\\nよくバレなかったものだと感心してしまう。"



833 = "しかも、どういう詐欺を使ったのか、\\n僕には『ヤエカの双子の姉』という戸籍まで与えられた。"



814 = "おかげで女性区の一般市民という立場を手に入れたのだけど、\\nまあ……召集とかもされてしまうのは副作用だろう。"



651 = "「ちょっと、ちょっとユイちゃん、どこまで行くの！」"



927 = "ヤエカと繋いでいた手を引っ張られ、我に返る。"



940 = "人がいない方に歩いてきたとはいえ、\\nいつの間にか周囲が廃墟ビルばかりになっていた。"



514 = "「……ここ、どこ？」"



749 = "「ユイちゃんが引っ張って来たんでしょ」"



708 = "「まあ、うん……そうだけど」"



777 = "「怖かったのはわかるけど、俯いてずんずん行っちゃうしさー」"



835 = "しかもだいぶぼんやりしていた。本当に身分証とか\\n大丈夫かなって、考え込んでいたものだから……。"



722 = "「も、戻ろうか」"



628 = "「そだね。なんか建物崩れてきそうで危ないっぽいし、\\nホテルも絶対こっちじゃないし」"



844 = "そういうわけで踵を返すものの、正直足が重かった。"



673 = "「ねえ……もし男だってバレたら、どうなると思う？」"



795 = "「良くて男性区に強制送還？」"



781 = "「最前線送りになるやつだ……悪ければ？」"



768 = "「女性区のど真ん中だし、いるだけで痴漢でしょ。\\n死刑じゃない？」"



724 = "「もう帰りたい……」"



616 = "「そういうわけにもいかないからここにいるんでしょ。\\nほら、勇気出して歩く。どっかでご飯も食べたいし」"



677 = "「はい……」"



1078 = "覚悟は決めたつもりだったけど、女の人だらけの街は\\n実際に来てみると、僕には怖すぎる場所だった。"



845 = "そうして、渋々ながら来た道を引き返したのだけど%p-1;%fＭＳ ゴシック;――"



509 = "「……あれ。ここさっきも通らなかった？」"



760 = "「全部似た景色だし自信ないけど、たぶん？」"



793 = "「結構歩いてる気がするんだけど……」"



728 = "「もしかして、迷った？」"



513 = "「……かも」"



1048 = "瓦礫だらけで全然真っ直ぐ歩けないし、行ったり来たり、\\nぐるぐるしているうちに、もはやどっちに行けばいいのかも\\n分からなくなってきた。"



675 = "「はぁぁ……ユイちゃんってば、この歳になって迷子とか」"



746 = "「ヤエカもでしょ！」"



622 = "「そこはお姉ちゃんが責任持って妹を導いてくれないと」"



690 = "「ふ、双子だし……そういう設定ってだけだけど」"



632 = "「そもそも、こんなややこしい所にボクを連れ込んだの、\\nユイちゃんだよね？」"



680 = "「はい、ごめんなさい……」"



972 = "全面降伏して、けれどもそれで何か状況が変わるわけでもない。"



674 = "「ねえ、ヤエカ……どうしよう？」"



588 = "「お姉ちゃ～ん、おなかすいたぁ～」"



720 = "「も、もうちょっと我慢して……\\nというか、実は道分かってたりしない？」"



819 = "からかわれてるだけかも知れないと、\\n一縷の望みを込めて訊いてみる。"



784 = "「残念ながら」"



571 = "「ううっ、まさか、こんな都会で遭難……？」"



942 = "人の気配がまるでしない巨大な廃墟街のど真ん中だから、\\nそれもあり得ない話でもない。"



548 = "「あ、でも女だらけの人混みよりは気が楽かも。\\nいっそのこと、このまま野宿にしない？」"



785 = "「殴るよ？　往生際が悪い。おいしいご飯とスイーツが\\nお預けとか、食べ物の恨みは恐ろしいからね？」"



605 = "「じょ、冗談だから。ごめん……」"



934 = "不安を紛らわせようと、そんな言い合いをしていると%p-1;%fＭＳ ゴシック;――"




538 = "「あ……あのぉ～」"



1057 = "突然背後から掛けられた声に、ビクッとしてしまう。"




631 = "「その、何かお困り……ですか？」"



842 = "すぐ近くの瓦礫を乗り越えながら、人影が姿を現す。\\nまさか、こんなに接近されるまで気づかなかったなんて。"







837 = "しくじった。何か、余計な会話を聞かれなかっただろうか？\\n完全に油断していたから自信がない。\\nあまり聞かれるべきじゃない台詞を言った記憶だけはある。"



1104 = "（今なら、他には誰もいない？　なら%p-1;%fＭＳ ゴシック;――%p;%fuser;）"



932 = "一瞬で浮かんだ物騒な考えを選択肢に加え、身構えたのと同時。"




689 = "「ひゃっ！？　わわっ……！」"



858 = "その人の足下の瓦礫が崩れて、大きくバランスを崩す。"



551 = "「あ、危なっ」"




699 = "「ふわわわぁぁっ！！？」"



1083 = "軽く見上げるくらいの高さから転落してくるその人に、\\n咄嗟に手を伸ばす。飛びかかって制圧できるよう\\n身構えていたから、反応は間に合ったけど%p-1;%fＭＳ ゴシック;――"



582 = "「えっ」"




736 = "「んきゃんんんっ！！？」"



954 = "何が起きたのか、ちょっとよく分からなかった。"



893 = "どこかに体の何かが引っかかったのか、受け止める直前で\\n落ちてきたその人の身体がぐるっと回って、その後視界が\\n真っ白になって……。"



719 = "「むぐ、むぐぐっ」"



1063 = "結局受け止めきれずに押し倒されたから、背中が痛い。\\nあとなんか、息がしにくい。苦しい。"



726 = "「もごっ……！」"




685 = "「ひうっ！？　あ、あのっ……」"



896 = "なんだ？　どうなっているんだ？"



888 = "とにかく落ち着いて、まずは状況を把握しようと\\n視界を塞ぐ何かを押しのける。"




688 = "「ひゃあ！？　す、スカートがっ……」"



506 = "「………………ふあ？」"



1047 = "状況を把握してなお、しばらく理解が追いつかなかった。"




542 = "「あ、あの、すす、すみません！　受け止めてもらって……\\nじゃなくて、あのっ、お怪我はありませんか！？」"



730 = "「ら、らいひょうふ……もごっ」"




692 = "「ふぁぁっ……！\\nそこ、息が当たるとくすぐったいよぉ～～っ」"



852 = "そこ、というのは、おそらく目の前のこの布で、\\nこれたぶんパンツだよね……！？"



812 = "ええと、つまり、この人は僕の顔の上に落ちてきて\\n股間を押しつけてきてるというわけで……。"



563 = "「いや、そうはならんでしょ」"



788 = "「現になってるからっ！」"




686 = "「ひゃあんっ！\\nあの、そ、そんなところでもぞもぞされると……！」"



547 = "「あ、ご、ごめん……！」"



1102 = "鼻先に押しつけられているのは、たぶん女の子の、\\nものすごくデリケートな部分で……\\nプニプニした感触がして、ちょっと湿っていた。"




607 = "「す、すみません、すぐにどきますから……！\\nんんっ……あ、あれ？」"



1068 = "股間が離れていく、かと思いきや全く動かなかった。\\nむしろ体勢が変わって余計に押しつけられてくる。"




684 = "「ひぃっ……な、なんで、んあっ！？」"



725 = "「もごごっ！？」"



1002 = "布越しだけど、鼻先が何かの割れ目に潜り込んでいく。\\nこれ絶対、入っちゃいけないところに入ってる！"




552 = "「あぁんっ、そ、そこ、はぁっ……」"



880 = "でもそれ以上に、鼻がふさがれて口にも尻が押しつけられて\\n完全に息が出来ない！"




643 = "「だ、だから、もぞもぞされると……ひああっ！？」"



727 = "「もごーっ！？」"



886 = "とにかくどいて欲しいと、\\n必死に手の届く太ももを叩いて訴える。"




553 = "「ああぁっ、そんな、だ、だめですぅぅぅっ～～～！」"



670 = "「なんだこれ……。あの～、とりあえず苦しいみたいだから、\\n立ってもらうわけには」"




613 = "「そ、それが、足が動かなくて」"



561 = "「あー、びっくりして腰が抜けちゃった？」"




718 = "「み、みたいです……やぁんっ！？」"



700 = "「ぷはっ！」"



1009 = "必死にもがいて、どうにか呼吸だけは確保する。"




570 = "「うぅ……もうしわけないです。あの、と、ところで」"



662 = "「な、なに？」"




583 = "「お、おしっこくさく……ないですか？」"



527 = "「……多少」"




694 = "「ふぇぇぇんっ、やっぱりぃ……！\\nごべんなさいぃぃぃぃ～～～～っっ！！！」"



910 = "もしかして、どこかその辺で済ませたばかりだったのか？"



897 = "なんてことを思いながら、ヤエカが助け起こそうと\\n手を伸ばすのを黙って見守るのだった……。"




702 = "「ほ、本当にすみませんでしたっっっ！！！」"



926 = "ヤエカが女の人を引っ張って助け起こし、僕も解放された。"



839 = "しばしその場にへたり込んだままペコペコ頭を下げ合って、\\nようやく落ち着いてきて立ち上がったのだけど……。"



668 = "「なんか、ああいう転け方、\\n昔の有名なマンガで見たことあるな～」"



660 = "「とんだトラブルだったよ、もう……」"




624 = "「そそ、そうですよね！　いきなり通りすがりの変な奴の\\nおしっこの染みたパンツ嗅がされるとか！」"



545 = "「あ、いや、そうじゃなくて。\\n別に怒ってはいないから落ち着いて」"



996 = "実家の倉にあった古いマンガのタイトルなんて、\\n身内ネタすぎて通じるわけがなかった。"



635 = "「それで、おねーさんは一体……？」"




556 = "「あっ、わ、わたしはアカリといいます。姫乃アカリです！」"



756 = "「何か、お困りのようだったので声を掛けたんですけど……」"



709 = "「まあ、うん。困ってはいた。道が分からなくなっちゃって」"



550 = "「あ、やっぱり迷子……」"



587 = "「お姉ちゃんがね？　ボクは黙って付いてってただけだから」"



612 = "「そ、そうなんですか？」"



707 = "「まあ……はい」"



557 = "「あっ、ボクはヤエカ。片桐ヤエカだよ。よろしくね」"



682 = "「はいっ、よろしくお願いしますっ」"



818 = "お前も名乗れという風に、ヤエカから肘で脇腹を突かれる。"



512 = "「……か、片桐ユイ」"



778 = "「急になに緊張してんの？」"



599 = "「し、してないし……！」"



883 = "というか、なんかこう、反応に困る！"



938 = "事故とはいえ女の人の、それも年頃な美少女の股間に\\n顔を突っ込んだんだ。"



829 = "これ、向こうから謝ってくれてるのは女の子同士だからで、\\n男だってバレたら裁判抜きで絞首刑なのでは？"



1106 = "（余計な会話も聞かれたかも知れないし、\\nやっぱり放っておくわけには……）"



944 = "今なら目撃者もいないだろうからどうにか出来るし、\\n廃墟の中なら死体を隠す場所にも困らない。"



861 = "それが安全策だと、理性が選択を迫ってくるのだけど……。"



544 = "「あ、あの、やっぱり怒ってません？」"



664 = "「ないです」"



654 = "「でも、あの……ちゃ、ちゃんとお詫びはしますので！」"



1072 = "若干不穏な空気が滲み出ていたのか、\\n焦った様子で再び頭を下げてくる。"



703 = "「ほほう、なんでもすると」"



579 = "「えっ、いえ、なんでもとまでは……。\\nで、でも、ちゃんと誠意は見せますので！」"



710 = "「まあいいでしょう、具体的には？」"



899 = "なんでヤエカが仕切っているんだ。被害者は僕なのに。"



577 = "「ええっと……目には目をとかいいますし、\\n同じことをやり返してください！\\nわたしの顔にもパンツを押しつけてください！」"



601 = "「しないよ！？　何その変態行為！\\nえっ、もしかしてそういう趣味？　されたいの？」"



648 = "「ちち違いますっ、そういうイジメを見たことがあって、\\nものすごーく屈辱的だったので、それをこっちがやって\\nしまったと思うと申し訳なくて……！」"



867 = "そんなイジメあるの？　女社会こわっ！"



656 = "「と、とにかく、\\nやりたくないしそういうお詫びはいらないから」"



604 = "「じゃあ、か、顔の上でおしっこしてもいいです……！」"



600 = "「しないから！　こっちが恥ずかしい！　なんなのキミ！」"



554 = "「あうあう……よ、余計に怒ってます？」"



645 = "「だから怒ってないってば……本当にもういいから」"



810 = "いきなり顔面に股間を押しつけてきたかと思えば、\\nまるでドＭみたいなお詫びばかり提案してくる美少女。"



1037 = "正直、調子が狂う。元々親切心で声を掛けてきたのだろうし、\\n危害を加える気力も削がれてしまう。"



653 = "「でしたら、あの、どうやってお詫びすれば」"



520 = "「……とりあえず、道を教えてもらえればそれで」"



742 = "「ボクたち迷子だし、それが一番助かるよねー」"



732 = "「わかりました！　目的の場所まで確実にお連れします！\\nあ、ついでに街の案内もします！　遠くから来られた\\nばかりなんですよね？」"



573 = "「うん、そだよー。田舎者のお上りさん。\\n荷物の量とかでわかっちゃうか」"







646 = "「ち、違いますよ！？\\n決して田舎の人を馬鹿にしているわけではなく！」"



715 = "「まだ何も言ってないから」"



962 = "僕の正体に繋がるような会話を聞かれていなかったか、\\n少し行動を共にして反応を探るのもありだろう。"



956 = "何も気づかれていないのなら、\\n別に積極的に始末したいわけではないのだから。"



603 = "「じゃあ……案内お願いします」"



729 = "「よろしくね、アカリちゃん」"



679 = "「はい、お任せ下さいっ！」"



1045 = "無防備な笑顔を見せられ、本当、気が抜けてしまう。"

