


0 = ""


1010 = "ユイ"
999 = "ミク"
998 = "マユミ"
988 = "アカリ"
1013 = "リン"
1002 = "ヤエカ"
1037 = "先輩女子Ａ"
1148 = "１年女子Ａ"
1012 = "ユイ・アカリ・ヤエカ"
1015 = "ルリコ"
1021 = "中村"
993 = "オートマタ"


1081 = "放送の声"
1036 = "先輩女子"
1147 = "１年女子"
1149 = "３人"






18 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;翌日。早朝０６００時。"



520 = "「……っ、おはようございます！」"



744 = "「はい、おはようございます」"



1075 = "懐かしい起床ラッパの響きで反射的に飛び起きると、\\n既にミク先輩もベッドから降りてくるところだった。"



861 = "「片桐学生は……新入生にしては反応が早いですね。\\nまるで訓練済みの兵隊みたいです」"



581 = "「えっ、あっ……ね、寝起きはいい方なので！」"



644 = "「そうですか、それは結構なことです。\\nここでの生活においては有利な体質だと思います」"



718 = "「ど、どうも」"



1109 = "特に疑問を掘りさげるつもりはなさそうで、\\nほっと胸をなで下ろす。"



959 = "つい反射的に起きてしまったけど、確かに素人らしくは\\nなかったかもしれない……気をつけないと。"




905 = "『起床～～起床～～。総員、お外に整列～～。\\n小隊ごとに点呼～～』"



967 = "と、天井に取り付けられているスピーカーから、\\n気の抜けるような教官の声が聞こえてくる。"



705 = "「では、片桐学生。５分以内に身支度を整えて整列です。\\n服装はそのまま作業服で、洗顔を済ませ寝癖も直すこと」"



749 = "「はい！」"



511 = "「……あと、姫乃学生も起こして連れてくるように」"



730 = "「は、はい……！」"



932 = "そう、『素人らしい』というのはこういうのを言うんだ。"



794 = "「んにゅ……、すやすや…………」"



1086 = "時刻はまだ早朝だ。起床ラッパが吹かれても、\\nすぐにパッと起きられないのも無理はない。"



627 = "「すや～～……」"



13 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;いや、でも放送も掛かったし、僕と先輩がすぐ側で割と\\nうるさくしているし、ここまで熟睡しているのは図太いな？"



540 = "「あ、アカリ、朝だよ。ほら、起きて」"



997 = "ベッドの脇から呼びかけるけれど、反応はない。"



795 = "「アカリ、あの……もう起きないとダメだよ」"



1061 = "布団の上から、おそるおそる、そっと体を揺すってみる。"



566 = "「う、う～～ん……」"



796 = "「アカリ、ちょっと……！」"



1134 = "起きあがってくるような反応はない。手強いな……！"



903 = "「５分以内ですよ。既に１分４５秒が経過。\\nちなみに遅刻は、理由はどうあれ連帯責任です」"



801 = "「アカリ！　アカリ！　早く起きてーー！！！」"



760 = "「ふにゃ……」"



612 = "「こうなったらしょうがない！　せーの……！」"



1089 = "最終手段として、掛け布団を掴んで一気に引き剥がす！"



758 = "「ふぁっ！？　えっ、あぅ……？」"



726 = "「なっ……えっ……？」"



935 = "そうして、布団を奪ってからようやく気がついた。\\nアカリがどういう格好で寝ていたのかを。"



590 = "「お、おはようございましゅ……？」"



695 = "「ちょっと、なんで服着てないの！？」"



528 = "「……？　下着はつけてるよぉ？」"



637 = "「そういう問題じゃなくて！」"



859 = "「温暖化は進む一方ですからねぇ……寝苦しくて～」"



873 = "「私もスリープ時は放熱効率を考えて下着です。\\n片桐学生は、服を着たままで暑くないのですか？」"



593 = "「お、お淑やかさに欠けますので……！」"



642 = "「そうでした。宗教上の理由が……失礼しました。\\nところで、既に残り２分を切りました」"



734 = "「は、早く服を着てーーーーっ！！！」"



757 = "「ひゃぅっ！？　な、なんですか？」"



1053 = "大慌てでアカリの体操服を掴んで押しつけつつ、\\n頭がクラクラしてきてしまう。"



955 = "だって目のやり場にものすごく困るし、なんだかむわっと\\nいい匂いが漂ってくるし、けれどそんなこと言ってる暇は\\n全くないわけで……！"



556 = "「いいから早く～～～っ！！！」"



1092 = "本当に……！　アカリといるとシリアスでいられない！"



943 = "その後、整列点呼と朝礼、ラジオ体操を済ませてからの、\\n寮内清掃の時間%p-1;%fＭＳ ゴシック;――"



504 = "……なのだけど。"



902 = "「１１３分隊、整列！！！」"



1027 = "何故か僕とアカリ、\\nついでにヤエカの３人は廊下に立たされていた。"



823 = "「休め！\\n……それで貴様ら、何故立たされているかは分かるか」"



586 = "「えっと……朝礼にちょびっと遅れたから？」"



650 = "「その通りだ。嘆かわしいことに我が１１３分隊は、\\n本日の朝礼にその全員が遅刻した」"



933 = "そう、あれからどれだけ急いでアカリに着替えさせても、\\n結局時間に間に合わせることは不可能だった。"



1006 = "ヤエカの方も決して寝起きのいい子ではないから、やっぱり\\n僕達と同じくらいのタイミングで飛び出してきていて……。"



714 = "「でも、遅刻っていってもほんの１分くらいですよぉ」"



630 = "「そ、それに、時間の方が短すぎるというか……\\nわたし達だけじゃなくて、他の分隊の人達もですし」"



693 = "「ちょ……ヤエカ、アカリっ」"



1116 = "確かに、今朝の点呼には\\n全生徒の半分くらいが間に合わなかったのだけど%p-1;%fＭＳ ゴシック;――"



557 = "「いいか貴様ら。『でもでもだってぇー』などと泣き言を\\n喚いて許されるのは、ママのおっぱいしゃぶって小便を\\n垂れ流す赤ん坊だけだ」"



701 = "「つまり貴様らは、乳臭いションベン垂れだというわけだな？」"



661 = "「それは流石に暴言……」"



895 = "「返事は『はい』か『イエス』だ。チビのションベン娘！\\n泣き言は許さんと言ったばかりだぞ？」"



567 = "「うぅ……はいっ！　申し訳ありません！」"



986 = "みんなも同じだからと、怒られないわけではないのだ。\\nだって……。"




548 = "「あんたら、揃いも揃って遅刻とかアタシに恥かかせて、\\n舐めてんの？」"




616 = "「ご、ごめんなさい……」"




618 = "「ごめんで済むならなぁーー！？\\n保安隊なんていらねーんだよっ！！！」"



501 = "……だって、ほかの人達も滅茶苦茶に怒られてる訳だし。"



620 = "「さて、あたしは優しい先輩だからな。\\n貴様らが乳臭いションベン垂れであると認めるのなら、\\n言い訳くらいは聞いてやろう」"



594 = "「おい、片桐%p-1;%fＭＳ ゴシック;――%p;%fuser;の姉の方。貴様は乳臭いションベン娘か？」"



1137 = "返事は『はい』か『イエス』。間違えてはいけない。"



743 = "「はい……！　自分は乳臭いションベン娘です！」"



561 = "「いいだろう、言い訳を認めてやろう。貴様はなぜ遅刻した？」"



748 = "「はい！　服を着るのに時間が掛かったからです！」"



787 = "「やれやれだ。\\n一人で着替えも出来ないヨチヨチ娘だったとはなぁ？」"



532 = "「あ、あのっ！　寝坊をして着替えに時間が掛かったのは\\nわたしです……！　ユイちゃんは、わたしに付き合って\\nお世話してくれただけで……」"



836 = "「姫乃学生。誰が発言を許可した？」"



624 = "「す、すみません……！　でもっ」"



815 = "「ヨチヨチ娘は自分だと名乗り出たのは、まあ正直でよろしい。\\nだがな、そんな貴様の世話を焼ききれなかったのは片桐姉が\\n無能だからだ。違うか、守屋学生」"



871 = "「私は姫乃学生を起こして連れ出すように指示しました。\\n片桐学生は任務を果たせなかったことになります」"



698 = "「つまり、連帯責任というわけだな。姫乃、貴様のせいで\\n片桐姉もこうして巻き添えを食らっているんだぞ？」"



729 = "「は、はい……。ごめんなさい……」"



984 = "みるみるアカリが萎れていくのが、手に取るようだった。\\n大丈夫かな、これ。"



545 = "「あの～、その理屈だと、\\nボクが遅刻したのもリン先輩の連帯責任になるんじゃ……」"



682 = "「だから許可なく発言するなと言っているだろうが」"



866 = "「発言よろしいでしょうかっ！」"



775 = "「まあいいだろう。確かに、貴様の世話を焼くのはあたしだ。\\n貴様を遅刻させた連帯責任は取らねばならんな」"



680 = "「だから、今朝のことはふか～く反省しているところなんだ。\\n優しく揺り起こすのではなく、最初から全力で踏みつけて\\n蹴り飛ばすべきだったと」"



580 = "「えっ……と」"



848 = "「明日からはそうするからな。\\nきちんと起きられそうで嬉しいか？」"



774 = "「ぼ、暴力はんたい……」"



897 = "「返事は『はい』か『イエス』です」"



747 = "「はい！　ありがとうございます！！！」"



918 = "うん、余計なことは言わないようにしよう。\\n墓穴を掘るだけだから……。"



659 = "「それにしても、貴様らには期待していたんだがなぁ？\\nもしかしたら優秀な連中が揃っているかもしれないって。\\n裏切られた気分だよ」"



510 = "「…………」"



891 = "「貴様らは無能揃いだった。一つ年上に過ぎないあたしの\\n目からでも、ヒヨッコどころかキモオスの精子レベルだ！」"



554 = "「いいか、今の貴様らには全く価値がない！　ゴミクズの\\nオタマジャクシだ！　自分の立場が分かったか精子共！」"



565 = "「ぅぅ………………」"



990 = "アカリが、涙目で気持ち悪そうにしていた。\\n……精子呼ばわりは、たぶん普通の女の子にとって、\\n僕が想像するよりはるかに侮蔑的なんだろう。"



685 = "「だが、安心しろ！\\nそんな精子共でも、我々が一人前になるまで鍛えてやる！\\nなぁに、死なない程度には加減するから怖がるな！」"



756 = "「ひぇぇっ……」"



719 = "「どうだ！　嬉しいか！　返事は！？」"




746 = "「はい！　ありがとうございますっ！！！」"



640 = "「そうか嬉しいか！　ならまずは腕立て伏せだ！\\n健全な精神は健全な身体に宿るからな！\\n姫乃学生、貴様は何回腕立て伏せが出来る？」"



617 = "「ご、５回くらいでしたら」"



668 = "「そんなんでよく保安隊に入ろうなどと思ったな？\\nいいだろう。我ながら手ぬるいが、まずは３０回だ！」"



572 = "「え……む、むり……」"



893 = "「返事は%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



733 = "「は、はい！　ありがとうございますっ！！！」"



785 = "「やる気になってくれてあたしは嬉しいぞ。\\nちなみに途中でへばったら素敵な罰ゲームがあるからな。\\n腕立てヨーイ！」"



1035 = "僕達は、やけくそになって床に伏せるのだった。"



751 = "「ひぃ、ひぃ、う、腕が上がらないよぉ……」"



570 = "「うぐぐ……ボクも。雑巾掛けがトドメだったねー」"



12 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;あの後、本当に腕立て伏せを限界までさせられて、\\n休憩もなしに寮の掃除。それが終わった頃には授業時間が\\n迫っていたので朝ごはんを掻き込んで教室まで走ってきた。"



877 = "「腕の感覚がなくて、\\nちゃんとごはん食べられなかったよ……」"



799 = "「アカリちゃんもユイちゃんに\\n食べさせてもらえばよかったのに」"



535 = "「あ、あれはちょっと恥ずかしくて」"



782 = "「やってる方も恥ずかしかったよ……。\\n『あーん』なんてやるの、お母さんじゃないんだから」"



603 = "「お母さんじゃなくてもお姉ちゃんだもーん」"



982 = "まったくもう、この甘えん坊は……。"



712 = "「でも、平気そうなユイちゃんはすごいよね。\\nわたし、結局腕立て伏せも３０回出来なかったよ……」"



808 = "「ボクもだし、普通無理だって。\\n涼しい顔で出来ちゃうユイちゃんがおかしい」"



629 = "「そ、そこまで余裕じゃなかったけど。かなりキツかったし」"



658 = "「それでも、３０回も出来るだけで十分にすごいと思う！」"



879 = "「腕力だけでそこまで言われても……！」"



1126 = "記憶にある男の大人達と比べれば、今の自分なんて\\nかなりひ弱な方だから、褒められても困ってしまう。"



948 = "それでもこんなに差がつくということは、\\nやっぱり女の子というのは身体の作りが違うのだろうな。"



777 = "「まー、ユイちゃんって『マザー』に選ばれて召集されて\\nきたわけだし。兵隊の素質ありってお墨付きだもん」"



700 = "「つまり、選ばれし者ってことだよね。かっこいい！」"



667 = "「そんなにキラキラした目で見ないで～～」"



1138 = "選考基準になったと思う運動能力テストでも、適当に手は\\n抜いていたんだけど……努力で選ばれたわけじゃないから、\\n本当に何もすごくはないんだ。"



764 = "「ふむ、そうですのね。片桐さんは召集組……\\n『マザー』から認められた有能、というわけですのね？」"



573 = "「え……？」"



911 = "いきなり背後から掛けられた声に振り向いて。"



597 = "「おーほっほっほっ！　素晴らしいですわ！\\n貴女、ワタクシのライバルに相応しいようですわね！」"



583 = "「えっ、ええっ……」"



974 = "なんか、お嬢様が下着姿で高笑いしていた！　なんで！？"



529 = "「あ、あのあの、ルリコさん！　服！　服忘れてます……！」"



839 = "「忘れてるわけじゃありませんわ！\\n貴女、ワタクシのこと馬鹿にしてらっしゃるの！？」"



628 = "「そ、そういうわけでは……！　でも、あのっ」"



623 = "「じゃあ、わざと服着てないってことだから……露出好き？」"



900 = "「違いますわよ！　趣味でもなくて！　これは……\\nそう、バカには見えない服なんですのよ？」"



767 = "「へー、ボクには見えないっぽい。確かにバカだし」"



599 = "「おーほほほほっ！　謙虚な自己評価をなさるのは、\\n愚か者なりにとても賢明な行いでしてよ！」"



542 = "「あの、その格好で高笑いはものすごくバカっぽいです……！」"



885 = "「貴女のそういうズバズバ言うところ、本当に苦手ですわ！」"



702 = "「で、その……結局裸ですよね？　どうして……」"



737 = "「はぁ……仕方ありませんわね、認めます。\\n確かにワタクシは服を着ていませんわ。ですがこれは、\\nそう、いわゆる伝統というものですわ」"



825 = "「伝統？」"




670 = "「そーそー、伝統の罰ゲーム。やらかした子が先輩に服を\\n取り上げられて、１日中ずっとこのカッコで過ごさなくちゃ\\nいけないんだってさ」"



638 = "「そういう訳ですわ。脱衣刑というらしいですわよ！\\n制服を着る資格がないという意味ですわね！」"



727 = "「なんで自慢げ。ちょっとは恥じらったら？」"




688 = "「だよねー、恥じらいのない人には効いてないよね。\\nちな、脱いだ服畳むのを断固拒否ったらこうなった」"



687 = "「だって、それは使用人である貴女の仕事でしょう？」"




690 = "「ちげーよ！　ただのルームメイトでしょ！？」"



1118 = "突然入ってきて説明をしてくれた子は、\\nルリコさんと同室の人らしい……大変そうだ。"



819 = "「ルリコさん、そういうのはきちんと自分でした方が。\\n次はもっと厳しく怒られちゃいますよ……？」"



937 = "そして、他のみんなは呆れたりイラッとしていたりするのに、\\nアカリだけが真っ直ぐにルリコさんを心配している。"



514 = "「……そう言われましても、自分で服を畳んだことなんて\\nありませんもの。上手く出来そうになくて」"




740 = "「はあああ！？　そういうことは早く言えって！\\n別に難しくないし、そんぐらい教えるから！」"



562 = "「いいんですの……？」"



792 = "「わたしも、そのくらいでしたらお教え出来ると思います！\\nいつでも頼ってください！」"



886 = "「貴女の世話にだけは、絶対なりませんわ！」"



666 = "「そんなっ！？」"



1049 = "変な意地を張っていたらしいが、丸く収まりそうで……\\nいや、問題は継続中なんだけど。"



696 = "「つ、つまり、ルリコさんは今日……ずっとその格好なの？」"



635 = "「そういうことですわね。ところで貴女、片桐ユイさん？\\n先程からずっと、あからさまに目を逸らしておりますわね？」"



608 = "「き、気にしないで」"



1041 = "分かってる。ここは女子のみの学校で、女の子同士だから\\n見ても構わないし目を逸らすのは不自然なんだって。"



962 = "でも、そう言われても目のやり場にはやっぱり困る……！"



766 = "「ふむ、貴女もしかして……」"



981 = "ま、まずい！？　もっと自然に、裸でも見つめないと……！"



821 = "「ワタクシの玉の肌が眩しすぎて、直視出来ないのですわね！\\nおーほほほほっ！　真の美しさを理解される方ですのね！」"



513 = "「……そ、それでお願いします」"



578 = "「え、そんなに？　わたしは……分かっていなかった？」"



564 = "「いや、あの……なんかこう、だめだこりゃ」"



14 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;それにしても、脱衣刑、か。"



691 = "「ちなみに途中でへばったら素敵な罰ゲームがあるからな。\\n腕立てヨーイ！」"



505 = "……まさか、先輩の言っていた罰ゲームって。"



914 = "いや、そうとは限らないけど、\\nでもそういう懲罰が存在しているのは確かなわけで。"



1146 = "（もし食らったら……一発でアウトだよ！）"



1055 = "宗教上の理由で避けられるかもしれないけれど、\\n懲罰となればそこまでの配慮を期待出来るかどうか。"



876 = "「絶対……失敗するわけにはいかない」"



973 = "なるべく目立たない程度に、模範的な学生を演じよう。"



601 = "「おーほほほほほっ！　ワタクシは美しい……！！！」"



1018 = "下着姿で高笑いをする変なお嬢様から目を逸らし、\\n僕は気を引き締めるのだった。"



569 = "「うぉらああーーっ！　走れ走れ走れーーーーーーっ！！！」"



753 = "「ひぃっ、ひぃぃぃぃんっ……！！！」"



1084 = "昼食を挟んで午後からは、実技の訓練が始まった。\\nこの学園のカリキュラムでは、基本的に午前が座学、\\n午後は実技ということになるらしい。"



502 = "……で、実技といってもまずは体力がなければ\\n何も始められないということらしく、今日はこうして\\nグラウンドを何周も走らされている。"



530 = "「あ、あのぉっ、ちょっとだけ休憩を%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



889 = "「貴様は敵に追われている時に休憩するのか！？\\n追いついたらそのガキ臭いケツ蹴り飛ばしてやるからな！」"



552 = "「あー、嫉妬っすか！？　自分のお尻がデカいからって、\\nボクのカワイイ小尻にヤキモチでーすかー！？」"



596 = "「おまっ……いい度胸だ！　本気であたしを敵に回したな！？」"



609 = "「くぅぅぅっ……！　田舎育ちを、なめるなぁ～～～～！」"



803 = "「クソガキがっ……！　待てやコラあああああああっ！！！」"



1039 = "全力で逃げるヤエカを、リン先輩が鬼の形相で追いかけていく。"



498 = "……あいつ、わざわざ怖い先輩を挑発して何やってるんだ。"



951 = "ただの反発心で刃向かっているだけなら自業自得だけど、\\n自分が目立つことでこっちに注意が向かないようにしている\\n可能性もあるからなあ……。"



1030 = "僕の秘密を守るために協力してくれているのなら感謝しか\\nないけれど、必ずしもそうとは限らないのが厄介だ。"



752 = "「ひぃっ、はぁっ……！　あっ……」"



541 = "「あっ、アカリっ！？」"



965 = "と、僕のすぐ後ろを走っていたアカリが、\\n足をもつれさせて思いっきり転んでしまっていた。"



525 = "「……怪我はありますか」"



755 = "「ひぅっ、はぁっ……！　だ、大丈夫、れすっ……！」"



909 = "あんまり大丈夫そうじゃない返事だったけど、\\n今にも死にそうな顔だったのはさっきからずっとなので\\nよく分からない。"



875 = "「立てますか？　手を」"



534 = "「あ、ありがと、ございまひゅっ……！」"



995 = "ゼイゼイと呼吸を乱しながら、\\n差し出された手に捕まって立ち上がる。"



759 = "「ふぅっ、はぁっ……す、すみません、走るの下手で」"



1132 = "走るのに上手い下手とかあるのか？　などと思いつつ、\\nアカリの手足をチェックする。"



522 = "「……どこか擦りむいてない？　痛いところは？」"



675 = "「だ、大丈夫……！　わたし、よく転ぶけど、\\nそのぶん転ぶのに慣れてるから！」"



841 = "「慣れるほど転ぶのはどうかと思いますが……確かに\\n外傷はないようです。動作にも異常は見当たりません」"



745 = "「はいっ、全然平気です！」"



519 = "「……ちょっと、肺と心臓は限界ですけど。はぁっ、ふぅっ」"



781 = "「もう結構走ってるもんね……あの、先輩」"



884 = "「負傷が認められないのであれば、休憩は不許可です」"



568 = "「うぅっ、厳しい……」"



850 = "「時間内に指定のノルマは走りきってもらいます。\\nまだ半分もこなしていませんし、現状のペースでは\\n間に合いません。息を整えたら再開して下さい」"



518 = "「……だそうだけど、いけそう？」"



604 = "「が、がんばります……けど、あの、\\nもし走りきれなかったら罰ゲームでしょうか？」"



647 = "「そうですね。一定のペナルティが課される予定です」"



622 = "「じゃ、じゃあ、無理そうなのでもう脱ぎます！」"



950 = "そんなことを言って、いきなり体操服のシャツを脱ぎ始めた！"



694 = "「ちょっ、なんで！？　待って待って、脱がないでっ！」"



1073 = "慌ててその手を掴んで止めたから、\\nなんとかおへそがチラ見えするくらいで済んだけど……。"



710 = "「でも、ちょっと無理そうだから……\\n朝の腕立て伏せの分もあるし、潔く罰を受けようかなって」"



807 = "「ペナルティが脱衣刑だとは一言も言っていませんが」"



584 = "「えっ、違うんですか？」"



898 = "「違います。今回のペナルティは、時間内に走りきれなければ\\n周回数が倍になります。朝の腕立て伏せの分は既にノルマに\\n加算済みで、走りきるまでは居残りです」"



632 = "「そ、それは%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



1026 = "体力がない奴は徹底的にしごいて鍛えるという宣言だった。"



728 = "「ぬ、脱ぐ方がいいんですけど」"



805 = "「ダメです。姫乃学生の呼吸、沈静化を確認。\\n速やかにランニングを再開して下さい」"



662 = "「そんな%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



835 = "「命令は下達済み。返事は」"



731 = "「は、はいぃっ、すぐに走りますぅぅ～～！」"



1001 = "ミク先輩に急かされて、再び僕らはランニングを始めた。"



927 = "さっきまでと同じく僕が先頭に立って、すぐ後ろにアカリ、\\nそして僕らを監視するように最後尾のミク先輩という隊列。"



1063 = "後ろから聞こえるアカリの呼吸を気遣いながら、\\nだだっ広いグラウンドを更に１周走った……のだけど。"



754 = "「ひぃっ、ひぐっ、はぅあっ……！」"



930 = "すぐにまた、\\n陸に打ち上げられてのたうち回る魚みたいになっていた。"



677 = "「だ、大丈夫……？」"



779 = "「むりでひゅ……！　これじゃ、ユイちゃん、までっ、\\nおいて、いって、くだひゃ、ぜぇぇっ……！」"



1024 = "今にも息絶えそうな声色で、\\n自分を置いて先に行けと訴えかけてくる。"



585 = "「えっと……」"



17 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;確かに、この状況ならそれが正解だろう。アカリの\\nペースに合わせていたらペナルティは避けられない。"



916 = "いや、今回のペナルティ自体はいいんだけど、\\nいちいち付き合っていたらすぐに余裕が持てなくなるし、\\nそれは新たな失敗の元凶だ。"



912 = "いつか大きな失敗をして脱衣刑を受けるような事態は\\n避けなければならないから、常に一定の余裕は確保して\\nおきたいわけで。"



707 = "「でも…………」"



739 = "「はぁっ……！　あぅっ……！　はぁっ……！」"



1023 = "今にも倒れそうだけど、アカリは必死に足を動かしている。"



543 = "「あの、ミク先輩。\\n姫乃さんを引きずっていってもいいでしょうか？」"



763 = "「ふへ！？」"



887 = "「貴女方はバディ、お互いが支え合うパートナーです。\\n無論、手を貸しても構いません」"



789 = "「わ、わたし、引きずられていくんですか……！？」"



831 = "「別に、ソリみたいに引っ張っていくわけじゃなくて……\\n肩を貸すから、倒れないように掴まってて」"



703 = "「で、でも、そんなことをしていたら」"



833 = "「別にアカリのペースに合わせたりはしないよ。\\nちゃんと付いてきて……いや、どっちかというと\\n無理矢理付いてきてもらうんだけど」"



588 = "「え゛っ」"



606 = "「がんばって。\\n付いてこられなかったら本当に地面を引きずっていくから」"



652 = "「その際は、私も片足くらいは引っ張りましょう」"



579 = "「えええええええええっ！！？」"



975 = "なんでこんな提案をしているのか、自分でもよく分からない。\\n明らかに足手まといだし、ハンデにしかならないのに。"



863 = "「片桐学生は、良い判断です。脱落者を出した場合、\\nどのみち連帯責任で全員ペナルティでしたから」"



537 = "「あ、そ、そうだったんですね」"



961 = "つまり僕は、無意識にそれを予期していたんだろう。"



512 = "「……じゃあ、あの、ごめんね？」"



1135 = "近づいてきたアカリの腕を取り、\\nこちらからも手を回して彼女の身体を支えるようにする。"



1128 = "負傷兵を運ぶ時なんかのやり方だけど……\\nいざ実行してみて気がついた。"



750 = "「ひあっ！？」"



925 = "これ、身体を寄せるとおっぱいが当たる……！\\nしかも汗ばんで熱くなってるアカリの身体が、\\nなんていうか妙に生々しくて。"



813 = "「ユイちゃん……？\\nあっ、もしかしてわたし、すっごく汗くさいとか」"



674 = "「だ、大丈夫……嫌なわけじゃないから」"



625 = "「すっごく嫌そうな顔で言ってるぅ！\\nやっぱり臭いんだーー！？」"



1093 = "本当に嫌なわけではないんだけど、変な気持ちになりそうで\\n息を止めていたら変な解釈をされてしまった。"



717 = "「と、とにかく、死ぬ気で走ってもらうからね……！」"



742 = "「はい……がんばりましゅ」"



1033 = "僕ももう覚悟を決めて、\\n半分アカリを抱えるようにしてよろよろと走り出す。"



1145 = "（うぅっ、柔らかい……あったかいよぉ！）"



1105 = "激しい動揺と罪悪感に翻弄されて、早くも後悔していた。"



1123 = "結局、アカリは時間内にゴール出来なかったから、\\n居残りで周回数追加に付き合わされることになった。"



946 = "それでも、日が沈んでしばらくした頃には体力訓練も終わり、\\n夕食、そして自習時間になる。"



797 = "「アカリ、夜もあんまり食べられなかったみたいだけど……\\n大丈夫かな」"



1095 = "机に向かって、授業の復習をしながら呟く。"



524 = "「……まあ、昼はちゃんと食べてたし大丈夫か」"



1051 = "夜中にお腹を鳴らしているようだったら、\\n買っておいたカロリーバーを夜食にあげようと思う。"



506 = "……何故か、涙目でお腹をきゅるきゅる鳴らしているのが\\n容易に想像出来るんだよね。"



762 = "「ふふっ」"



939 = "そして、僕は何を笑っているんだろう……？\\n今は部屋に一人だからいいものの。"



858 = "「油断しすぎだよ、私」"



15 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;ちなみに、僕以外のみんなはお風呂に行っている。\\n交代でお風呂に入る関係もあって、夕食から就寝までは\\n自習という名前の自由時間になっているのだ。"



1029 = "僕だけは、特例が認められて一番最後に入るのだけど……。"



853 = "「最後って、お湯は冷めてるし汚れてるし……」"



1083 = "昨日の夜のお風呂を思い出して、小さくため息を吐く。"



499 = "……たくさんの同年代の女の子の汗や垢や毛が混じった\\nお湯に浸かるのは、別に興奮なんてしなかった。決して。"



761 = "「ふひゃっ！？　は、はい！　どうぞっ！」"



978 = "ほんのちょっぴり悶々としていたところでドアをノックされ、\\n慌てて立ち上がる。"



804 = "「シツレイ　シマス　洗濯物ノ　回収　デス」"



538 = "「あ、はい。ご苦労様です」"



1038 = "入ってきたのは、寮内の雑用を受け持つオートマタだった。"



1112 = "男性軍にいた頃は、高価なオートマタに雑用をさせるなんて\\n考えもしなかったものだけど……。"



649 = "「そこの籠にまとめてあるので全部です。お願いします」"



802 = "「カシコマリ　マシタ」"



1101 = "洗濯籠を抱えて、オートマタは廊下に戻っていく。\\nちらりと覗き見れば、台車に山のような洗濯物を\\n積み重ねて運んでいた。"



523 = "「……まあ、助かるけど」"



1077 = "戦闘員になる前は雑用係で同じ事をさせられていたから、\\n大変さはよく分かっている。\\nだからちょっとだけ、申し訳ない気持ちになってしまう。"



1096 = "機械相手に何を……と、一人ため息をつく。"



784 = "「やっほ、ユイちゃん。ただいま～」"



812 = "「ヤエカはこの部屋じゃないでしょ」"



941 = "そしてオートマタと入れ替わるように、風呂上がりのヤエカが\\n入ってくる。その後ろには、アカリとミク先輩も一緒だった。"



735 = "「はぁ……お風呂って、こんなに気持ちよかったんですね～」"



856 = "「汗を流しただけでなく、筋肉の疲労が大きいためでしょう。\\nしっかりとストレッチを行うことを推奨します」"



732 = "「は、はいっ、やってみます……！」"



1008 = "ヤエカはともかく、お風呂上がりのアカリとミク先輩から\\nふわりと石鹸の香りが漂ってくる。火照った肌の色合いも\\nなんだか色っぽくて、ドキドキしてしまう。"



860 = "「片桐学生。何かソワソワしていますが」"



720 = "「な、なんでもないです……！　お気になさらずに！\\nところで、ヤエカは何しに来たのさ」"



559 = "「いいじゃん、話相手にくらいなってよ～。リン先輩は\\nどっか行っちゃったし、部屋に戻っても１人なんだもん」"



1058 = "寮生活で１人になれるのはむしろ贅沢な時間のはずだけど、\\n流石にまだ２日目だから話したいことが沢山あるんだろう。"



817 = "「リンは分隊長ミーティングに出席していますので、\\nしばらくは戻ってきません」"



770 = "「ほほう、そうなんですね！\\nじゃあ、今ならあの鬼隊長の悪口言い放題ってこと！？」"



810 = "「ミク先輩から本人に伝わるとか考えないの？」"



811 = "「ミク先輩なら言わないって信じてる！」"



829 = "「内容にも寄りますが、秘匿要請、了承しました」"



536 = "「あ、いいんだ？　ミク先輩大好きー♪」"



521 = "「……ど、どうも」"



1108 = "照れてる……！　ちゃんと感情があるんだって、少し驚いた。"



656 = "「それで、リンが何かしましたか？　過度なハラスメントを\\n受けているなら、私からも改善の要求をしますが」"



854 = "「本当ですか！？　聞いて下さいよー！\\n実は、夕飯が終わって部屋に戻ったら%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



724 = "「な、何これーーっ！？　ボクの荷物、\\nグチャグチャになって床にぶちまけられてる！」"



882 = "「荷物検査をしておいたぞ。校則違反は無いようだが、\\n散らかって見苦しいから早く片付けろ」"



826 = "「先輩がやったんじゃん！」"



683 = "「だから？　隊長の命令に逆らうのか？　不服従か？\\n貴様がじっくり反省出来る懲罰はなんだろうなぁ？」"



610 = "「ぐぬぬっ……」"



846 = "「文句がないならさっさと身体を動かせ！　クソチビが！」"



508 = "「%p-1;%fＭＳ ゴシック;――%p;%fuser;ってことがあって！　酷くない！？」"



551 = "「あー……うん、まあ」"



867 = "「確かに、言い方はちょっとよくないかもだけど……」"



547 = "「あれ、なんか微妙な反応」"



880 = "「荷物検査は、わたし達も受けたから。\\n部屋が荒らされてたのも一緒だよ」"



672 = "「そーなの？　みんなやられてるってこと？」"



953 = "ただまあ、僕達の場合は%p-1;%fＭＳ ゴシック;――"



845 = "「所持品検査を行いました。では、片付けて下さい」"



539 = "「あ、はい」"







772 = "「ほら、ミク先輩ってあんまり怖くないから……。\\n別に意地悪されてるわけじゃなさそうかなって」"



1103 = "淡々とした報告と指示に、呆気に取られながらも\\n普通に従ってしまったのだった、"



614 = "「こっちの部屋いいなー！　ボク、片付けてる時も\\nメッチャ嫌味ばっかり言われたんだけど！？」"



602 = "「お尻が大きいとか言うから。喧嘩売ったようなものでしょ」"



613 = "「こっちだってガキだのチビだの言われたもん！」"



1004 = "ヤエカって、背が伸びないことに\\nちょっぴりコンプレックスがあるからなぁ。"



722 = "「な、仲良くした方がいいと思うよ……？\\n同じ部屋で一緒に暮らす先輩なんだから……」"



830 = "「分かってるけどー……」"



1122 = "納得がいかないのか、ムスっとしていた。"



654 = "「それで、ミク先輩。結局あれはなんだったんですか？\\n全員やられてるってことは、何か意味があるんですよね？」"



634 = "「そう、ですね。貴女はなんの意味があると思いますか？」"



1130 = "質問に、質問で返されてしまう。\\nまるで口述試験のような口ぶりだった。"



574 = "「え、ええと……こういうのに慣れろ、みたいな訓練とか」"



611 = "「こういうのって？」"



843 = "「戦争だと、近くに砲弾が落ちてきただけで部屋の中が\\n滅茶苦茶になったりするし、そこから急いで荷物まとめて\\n移動とか、普通にある……ような気がするし」"



516 = "「……その通りです。加えて、災害現場などでも理不尽に\\n散らかった環境に身を置くことになります。そしてそれを\\n片付けるのが我々の任務です」"



697 = "「つまり、理不尽な目に遭うことにも慣れろってことですね」"



589 = "「えー、慣れたくないんだけど……」"



563 = "「いざって時に文句しか言えない人は邪魔なだけでしょ」"



847 = "「新兵とは思えない回答ですね」"



923 = "ぎくりとするようなことを言われてしまう。"



575 = "「え、えっと……！　どのみち兵隊にはなるんですし、\\n将来のことを色々と想像してみたりしましたのでっ！」"



591 = "「お、お姉ちゃんって妄想癖みたいなのあるからねー！\\n普通そこまでリアルな想像できないって！」"



646 = "「そうですか、なるほど……」"



972 = "な、なんとか誤魔化せただろうか？"



736 = "「はぁ……やっぱり、ユイちゃんはすごいなぁ」"



673 = "「ただの妄想だから、すごくはないよ？」"



715 = "「でもわたし、そこまでリアルに考えてなかったよ。\\n早く一人前になるには、そういうのも大切なのかなって。\\n理想を持ってるだけじゃ、やっぱりダメだよね」"



865 = "「理想って。なんかエリートっぽいこと言ってる」"



582 = "「えっ、あれ？　でも、みんなにも志望動機とかあるよね？」"



869 = "「私は召集されてきただけだから。\\n拒否して非国民みたいな履歴が残るのも嫌だし……」"



704 = "「で、ボクはそんなユイちゃんにくっついてきただけ」"



648 = "「そうなんだ……普通はそういう感じなの？　わたしが変？」"



664 = "「そんなことないって。\\nちゃんとした目的意識がある方がいいに決まってる」"



1125 = "苦笑しながら、困り顔のアカリを励ましてみる。"



963 = "でも、そっか。アカリにはちゃんとここにいる理由とか\\n目標みたいなものがあるんだな。"



1098 = "死にそうな顔になりながらも、\\n一生懸命に最後まで走ったアカリの姿を思い出す。"



907 = "あんな風に限界まで頑張れるのは、\\n自分の抱く理想に燃えているからなのだろうか？"



957 = "だとしたら、それはなんだか羨ましくて%p-1;%fＭＳ ゴシック;――"



653 = "「それで、アカリの志望動機ってどういうやつ？」"



1066 = "応援してあげたいなって思いながら、僕は尋ねてみた。\\n……だけど。"



587 = "「えっとね、男を皆殺しにすることだよっ」"



16 = "%p-1;%fＭＳ ゴシック;――%p;%fuser;元気よく言われて、固まってしまう。"



577 = "「え、えーと……それはちょっと、過激なのでは」"



526 = "「……？　そうかな？」"



922 = "きょとんと、不思議そうに首を傾げている。"



790 = "「わたしね、昔から正義のヒロインに憧れてたの。それでね、\\n強い女性になって、悪い男をみんなやっつけるんだよ！」"



983 = "まるで、子供が無邪気に夢を語るみたいに、アカリは笑う。"



827 = "「公式には、現在も男性による国防軍は味方ですが%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



708 = "「でも、そんなのもう誰も信じてませんよ？　子供を作るのに\\n男の人も必要だから、仕方なく受け入れているだけで」"



1040 = "分かっていたはずだけど……これが現実。"



1111 = "男は憎むべき敵。それが、この世界での常識だった。"



837 = "「実は、わたしのお母さんも保安隊の隊員だったんです。\\n今は除隊してますけど、５年前にはあの反乱軍と戦って、\\n平和を守ってくれたんです」"







678 = "「だから、わたしもいつか、\\nすごく格好いいお母さんみたいになりたくて%p-1;%fＭＳ ゴシック;――%p;%fuser;」"



868 = "「私、そろそろお風呂に行ってくるね」"



1088 = "最後まで聞かずに、用意してあった着替えを手に立ち上がった。"



527 = "「……？　まだちょっと早くない？」"



550 = "「あんまりのんびりしてるとお湯が冷めちゃうし」"



1032 = "僕は、上手く笑えているだろうか。"



768 = "「ほ、他のみんなが出たらすぐ入るんだよね……！\\nいってらっしゃい！」"



571 = "「うん、いってきます」"



1062 = "廊下に出てドアを閉め、大きく息を吐く。"



852 = "「最初から、分かってたよ……敵同士だって」"



1090 = "期待なんてしていなかった。何も。\\n僕の味方は、義母さんとヤエカだけなんだから。"



945 = "その日の汚れたお湯は、ただ気持ち悪いだけだった。"

